### ISSUE TITLE
forward  function has encounter unexpected "head_mask"

### ISSUE THREAD

**Issue by alice-cool** [j-min/VL-T5#15]

**Comment by alice-cool** [comment]
![image](https://user-images.githubusercontent.com/16870890/153115921-1708c870-dd83-418d-b853-6331d6eb0b54.png)

**Comment by alice-cool** [comment]
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 3
wandb: You chose 'Don't visualize my results'
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
wandb: WARNING Symlinked 39 files into the W&B run directory, call wandb.save again to sync new files.
  0%|                                                                                         | 0/13439 [00:00<?, ?it/s]Traceback (most recent call last):
  File "src/gqa.py", line 463, in <module>
    main_worker(args.local_rank, args)
  File "src/gqa.py", line 434, in main_worker
    trainer.train()
  File "src/gqa.py", line 189, in train
    results = self.model.module.train_step(batch)
  File "/home/byd/VL-T5/VL-T5/src/gqa_model.py", line 25, in train_step
    return_dict=False
  File "/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/byd/VL-T5/VL-T5/src/modeling_t5.py", line 451, in forward
    return_dict=return_dict,
  File "/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/byd/VL-T5/VL-T5/src/modeling_t5.py", line 281, in forward
    output_attentions=output_attentions,
  File "/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'head_mask'

wandb: Waiting for W&B process to finish, PID 28655... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/byd/VL-T5/VL-T5/wandb/offline-run-20220209_111944-3ncib413
wandb: Find logs at: ./wandb/offline-run-20220209_111944-3ncib413/logs/debug.log
wandb:
Traceback (most recent call last):
  File "/home/anaconda3/envs/pytorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/pytorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/pytorch/bin/python', '-u', 'src/gqa.py', '--local_rank=0', '--distributed', '--multiGPU', '--train', 'train,valid', '--valid', 'testdev', '--test', 'submit', '--optim', 'adamw', '--warmup_ratio', '0.1', '--clip_grad_norm', '5', '--lr', '5e-5', '--epochs', '20', '--num_workers', '4', '--backbone', 't5-base', '--output', 'snap/gqa/VLT5', '--load', 'snap/pretrain/VLT5/Epoch30', '--num_beams', '5', '--batch_size', '80', '--valid_batch_size', '100']' returned non-zero exit status 1.

**Comment by TaoHeyi** [comment]
> Some file spell the wrong word "transormer" with transformer

It might be that your transformer package version is higher than that required for this model
