### ISSUE TITLE
Error when finetuning RefCOCO with BART

### ISSUE THREAD

**Issue by zuujhyt** [j-min/VL-T5#22]
Hi, by running ```bash scripts/RefCOCOg_VLBart.sh 1```
I got the following error:
```
Original Traceback (most recent call last):
  File "/home/zuujhyt/miniconda3/envs/vlt5/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zuujhyt/miniconda3/envs/vlt5/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zuujhyt/miniconda3/envs/vlt5/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zuujhyt/test/VL-T5/VL-T5/src/refcoco_data.py", line 243, in __getitem__
    if self.args.vis_pointer:
AttributeError: 'Config' object has no attribute 'vis_pointer'

```

any advice?
thanks.

**Comment by j-min** [comment]
Hi, `args.vis_pointer` should be `False`. I updated the default argument in the repo.
